//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentInfraction
    {
        public int Id { get; set; }
        public int InspectoraReportId { get; set; }
        public int PaymentAgreementId { get; set; }
    
        public virtual InspectoraReport InspectoraReport { get; set; }
        public virtual PaymentAgreement PaymentAgreement { get; set; }
    }
}
