//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FineCalculationDetail
    {
        public int Id { get; set; }
        public string formulario { get; set; }
        public string percentage { get; set; }
        public string TotalCalculo { get; set; }
        public int InformationInfractionsId { get; set; }
        public int valueSmldvId { get; set; }
        public int TypeInfractionId { get; set; }
    
        public virtual valueSmldv valueSmldv { get; set; }
        public virtual TypeInfraction TypeInfraction { get; set; }
    }
}
