//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FineCalculationDetail1
    {
        public int id { get; set; }
        public string formula { get; set; }
        public decimal totalCalculation { get; set; }
        public int valueSmldvId { get; set; }
        public int typeInfractionId { get; set; }
        public decimal SmldvValueAtCreation { get; set; }
        public bool active { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime created_date { get; set; }
    
        public virtual Infraction Infraction { get; set; }
        public virtual valueSmldv1 valueSmldv { get; set; }
    }
}
