//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StateInfration> StateInfrationSet { get; set; }
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Infraction> Infraction { get; set; }
        public virtual DbSet<notifications> notifications { get; set; }
        public virtual DbSet<notificationSetting> notificationSetting { get; set; }
        public virtual DbSet<PasswordResetCodes> PasswordResetCodes { get; set; }
        public virtual DbSet<refreshTokens> refreshTokens { get; set; }
        public virtual DbSet<DocumentInfraction> DocumentInfraction { get; set; }
        public virtual DbSet<FineCalculationDetail> FineCalculationDetail { get; set; }
        public virtual DbSet<InspectoraReport> InspectoraReport { get; set; }
        public virtual DbSet<installmentSchedule> installmentSchedule { get; set; }
        public virtual DbSet<PaymentAgreement> paymentAgreement { get; set; }
        public virtual DbSet<TypeInfraction> TypeInfraction { get; set; }
        public virtual DbSet<TypePayment> typePayment { get; set; }
        public virtual DbSet<UserInfraction> userInfraction { get; set; }
        public virtual DbSet<UserNotification> userNotification { get; set; }
        public virtual DbSet<valueSmldv> valueSmldv { get; set; }
        public virtual DbSet<AuthSession> AuthSession { get; set; }
        public virtual DbSet<Form> form { get; set; }
        public virtual DbSet<formmodule> formmodule { get; set; }
        public virtual DbSet<Module> module { get; set; }
        public virtual DbSet<Permission> permission { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<Rol> rol { get; set; }
        public virtual DbSet<RolFormPermission> rolformpermission { get; set; }
        public virtual DbSet<RolUser> roluser { get; set; }
        public virtual DbSet<User> user { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<documentType> documentType { get; set; }
        public virtual DbSet<municipality> municipality { get; set; }
        public virtual DbSet<PaymentFrequency> paymentFrequency { get; set; }
    }
}
