//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuloForm
    {
        public int Id { get; set; }
        public int FormId { get; set; }
        public int ModuleId { get; set; }
    
        public virtual Form IdForm { get; set; }
        public virtual Module Module { get; set; }
    }
}
