//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Collections.Generic;
    
    public partial class notifications
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public int Type { get; set; }
        public int Priority { get; set; }
        public int Status { get; set; }
        public int RecipientUserId { get; set; }
        public string ActionRoute { get; set; }
        public Nullable<System.DateTime> ReadAt { get; set; }
        public Nullable<System.DateTime> ExpiresAt { get; set; }
        public bool active { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime created_date { get; set; }
    
        public virtual user1 user { get; set; }
    }
}
