//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentAgreement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentAgreement()
        {
            this.TypePayment = new HashSet<TypePayment>();
            this.DocumentInfraction = new HashSet<DocumentInfraction>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        public string Neighborhood { get; set; }
        public string FinanceAmount { get; set; }
        public string AgreementDescription { get; set; }
        public int UserInfractionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypePayment> TypePayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentInfraction> DocumentInfraction { get; set; }
        public virtual UserInfraction UserInfraction { get; set; }
        public virtual PaymentFrequency PaymentFrequency { get; set; }
    }
}
