//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentAgreement1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paymentAgreement1()
        {
            this.DocumentInfraction = new HashSet<DocumentInfraction1>();
            this.installmentSchedule = new HashSet<installmentSchedule>();
        }
    
        public int id { get; set; }
        public string address { get; set; }
        public string neighborhood { get; set; }
        public string AgreementDescription { get; set; }
        public Nullable<System.DateTime> expeditionCedula { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime AgreementStart { get; set; }
        public System.DateTime AgreementEnd { get; set; }
        public int userInfractionId { get; set; }
        public int paymentFrequencyId { get; set; }
        public int typePaymentId { get; set; }
        public decimal BaseAmount { get; set; }
        public decimal AccruedInterest { get; set; }
        public decimal OutstandingAmount { get; set; }
        public Nullable<int> Installments { get; set; }
        public Nullable<decimal> MonthlyFee { get; set; }
        public bool IsPaid { get; set; }
        public bool IsCoactive { get; set; }
        public Nullable<System.DateTime> CoactiveActivatedOn { get; set; }
        public Nullable<System.DateTime> LastInterestAppliedOn { get; set; }
        public bool active { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentInfraction1> DocumentInfraction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installmentSchedule> installmentSchedule { get; set; }
        public virtual paymentFrequency1 paymentFrequency { get; set; }
        public virtual typePayment1 typePayment { get; set; }
        public virtual userInfraction1 userInfraction { get; set; }
    }
}
