//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolformpermission1
    {
        public int id { get; set; }
        public int rolid { get; set; }
        public int formid { get; set; }
        public int permissionid { get; set; }
        public bool active { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime created_date { get; set; }
    
        public virtual form1 form { get; set; }
        public virtual permission1 permission { get; set; }
        public virtual rol1 rol { get; set; }
    }
}
