//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeInfraction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeInfraction()
        {
            this.UserInfraction = new HashSet<UserInfraction>();
            this.FineCalculationDetail = new HashSet<FineCalculationDetail>();
        }
    
        public int Id { get; set; }
        public string Type_Infraction { get; set; }
        public string Numer_smldv { get; set; }
        public string Description { get; set; }
        public int UserId { get; set; }
        public int DocumentInfractionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfraction> UserInfraction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FineCalculationDetail> FineCalculationDetail { get; set; }
    }
}
