//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Collections.Generic;
    
    public partial class userNotification1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userNotification1()
        {
            this.userInfraction = new HashSet<userInfraction1>();
        }
    
        public int id { get; set; }
        public string message { get; set; }
        public System.DateTime shippingDate { get; set; }
        public bool active { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userInfraction1> userInfraction { get; set; }
    }
}
