//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfraction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfraction()
        {
            this.PaymentAgreement = new HashSet<PaymentAgreement>();
        }
    
        public int Id { get; set; }
        public string DateInfraction { get; set; }
        public string stateInfraction { get; set; }
        public string observations { get; set; }
        public int UserId { get; set; }
        public int TypeInfractionId { get; set; }
    
        public virtual User User { get; set; }
        public virtual TypeInfraction TypeInfraction { get; set; }
        public virtual UserNotification UserNotification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentAgreement> PaymentAgreement { get; set; }
    }
}
