//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Collections.Generic;
    
    public partial class userInfraction1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userInfraction1()
        {
            this.paymentAgreement = new HashSet<paymentAgreement1>();
        }
    
        public int id { get; set; }
        public System.DateTime dateInfraction { get; set; }
        public int stateInfraction { get; set; }
        public string InformationFine { get; set; }
        public int UserId { get; set; }
        public int InfractionId { get; set; }
        public int numer_smldv { get; set; }
        public int UserNotificationId { get; set; }
        public decimal amountToPay { get; set; }
        public Nullable<decimal> smldvValueAtCreation { get; set; }
        public bool DiscountLocked { get; set; }
        public bool IsCoactive { get; set; }
        public Nullable<System.DateTime> CoactiveActivatedOn { get; set; }
        public Nullable<System.DateTime> LastInterestAppliedOn { get; set; }
        public decimal AccruedInterest { get; set; }
        public decimal InitialAmount { get; set; }
        public int DaysOfDelay { get; set; }
        public decimal TotalToPay { get; set; }
        public Nullable<System.DateTime> paymentDue3Days { get; set; }
        public Nullable<System.DateTime> paymentDue15Days { get; set; }
        public Nullable<System.DateTime> paymentDue25Days { get; set; }
        public Nullable<System.DateTime> paymentDue30Days { get; set; }
        public Nullable<System.DateTime> paymentDue40Days { get; set; }
        public int StatusCollection { get; set; }
        public bool active { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime created_date { get; set; }
    
        public virtual Infraction Infraction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paymentAgreement1> paymentAgreement { get; set; }
        public virtual user1 user { get; set; }
        public virtual userNotification1 userNotification { get; set; }
    }
}
