//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram1
{
    using System;
    using System.Collections.Generic;
    
    public partial class user1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user1()
        {
            this.notifications = new HashSet<notifications>();
            this.userInfraction = new HashSet<userInfraction1>();
            this.roluser = new HashSet<roluser1>();
        }
    
        public int id { get; set; }
        public string PasswordHash { get; set; }
        public string email { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> documentTypeId { get; set; }
        public string documentNumber { get; set; }
        public bool EmailVerified { get; set; }
        public string EmailVerificationCode { get; set; }
        public Nullable<System.DateTime> EmailVerificationExpiresAt { get; set; }
        public Nullable<System.DateTime> EmailVerifiedAt { get; set; }
        public bool active { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notifications> notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userInfraction1> userInfraction { get; set; }
        public virtual person1 person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roluser1> roluser { get; set; }
        public virtual documentType1 documentType { get; set; }
    }
}
