version: '3.8'

services:
  # 🌐 API principal - QA
  alcaldiafetch-api-qa:
    container_name: alcaldiafetch-api-qa
    build:
      context: ../..
      dockerfile: WebGESCOMPH/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5101:8080"
    networks:
      - alcaldiafetch_network
    labels:
      - com.alcaldiafetch.environment=qa

networks:
  alcaldiafetch_network:
    external: true